/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Book;
import Model.Borrow;
import Model.Client;
import Model.DVD;
import Model.Magazine;
import Model.Resource;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ryan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    //private ClientUI clientUI;
    
    public ArrayList<Resource> resourceList;
    
    
    public ArrayList<Borrow> borrowedList;
    
    
    
    public Client currentUser;
    
    public Resource foundID;
    
    
    
    DefaultListModel listModel = new DefaultListModel();
    
    public Login() {
        initComponents();
        
        createResources();
        
        borrowedList = new ArrayList();
        
        
        
        //Make all panels except the Log in panel invisible
        jUserPanel.setVisible(false);
        jResourceListPanel.setVisible(false);
        jClientResourcePanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jAdminMessagePanel.setVisible(false);
        jMessageBoardPanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jUserBooksPanel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainUserPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLoginPanel = new javax.swing.JPanel();
        jUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jUserPanel = new javax.swing.JPanel();
        jWelcome = new javax.swing.JLabel();
        jLogoutButton = new javax.swing.JButton();
        jMessageBoardPanel = new javax.swing.JPanel();
        jMessageBoard = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jAdminMessagePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jResourceListPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jClientResourcePanel = new javax.swing.JPanel();
        jRent2Button = new javax.swing.JButton();
        jRent6Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jIdSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jResponse = new javax.swing.JTextField();
        jAvailable = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jResourceList = new javax.swing.JTextArea();
        jUserBooksPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBorrowedResources = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDueOverdue = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMainUserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Apex Library Resource Management");

        jLabel1.setText("Username:");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLoginButton.setText("Log In");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1))
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUserName)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLoginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLoginButton)
                .addContainerGap())
        );

        jWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jWelcome.setText("Welcome User");

        jLogoutButton.setText("Log Out");
        jLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jUserPanelLayout = new javax.swing.GroupLayout(jUserPanel);
        jUserPanel.setLayout(jUserPanelLayout);
        jUserPanelLayout.setHorizontalGroup(
            jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWelcome)
                .addGap(36, 36, 36)
                .addComponent(jLogoutButton)
                .addGap(34, 34, 34))
        );
        jUserPanelLayout.setVerticalGroup(
            jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLogoutButton))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jMainUserPanelLayout = new javax.swing.GroupLayout(jMainUserPanel);
        jMainUserPanel.setLayout(jMainUserPanelLayout);
        jMainUserPanelLayout.setHorizontalGroup(
            jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
            .addGroup(jMainUserPanelLayout.createSequentialGroup()
                .addGroup(jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMainUserPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainUserPanelLayout.setVerticalGroup(
            jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMessageBoardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setVerifyInputWhenFocusTarget(false);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(1);
        jTextArea3.setRows(5);
        jTextArea3.setText("TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT TEST TEXT ");
        jTextArea3.setToolTipText("");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setAutoscrolls(false);
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextArea3);

        javax.swing.GroupLayout jMessageBoardLayout = new javax.swing.GroupLayout(jMessageBoard);
        jMessageBoard.setLayout(jMessageBoardLayout);
        jMessageBoardLayout.setHorizontalGroup(
            jMessageBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jMessageBoardLayout.setVerticalGroup(
            jMessageBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jAdminMessagePanelLayout = new javax.swing.GroupLayout(jAdminMessagePanel);
        jAdminMessagePanel.setLayout(jAdminMessagePanelLayout);
        jAdminMessagePanelLayout.setHorizontalGroup(
            jAdminMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdminMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        jAdminMessagePanelLayout.setVerticalGroup(
            jAdminMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdminMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Message Board");

        javax.swing.GroupLayout jMessageBoardPanelLayout = new javax.swing.GroupLayout(jMessageBoardPanel);
        jMessageBoardPanel.setLayout(jMessageBoardPanelLayout);
        jMessageBoardPanelLayout.setHorizontalGroup(
            jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessageBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                        .addComponent(jAdminMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jMessageBoardPanelLayout.setVerticalGroup(
            jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jMessageBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAdminMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(594, Short.MAX_VALUE)))
        );

        jResourceListPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRent2Button.setText("Rent - 2 weeks");
        jRent2Button.setEnabled(false);
        jRent2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRent2ButtonActionPerformed(evt);
            }
        });

        jRent6Button.setText("Rent - 6 weeks");
        jRent6Button.setEnabled(false);
        jRent6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRent6ButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Borrowing");

        jIdSearch.setColumns(1);
        jIdSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setText("ID");

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jResponse.setEditable(false);
        jResponse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResponseActionPerformed(evt);
            }
        });

        jAvailable.setEditable(false);

        javax.swing.GroupLayout jClientResourcePanelLayout = new javax.swing.GroupLayout(jClientResourcePanel);
        jClientResourcePanel.setLayout(jClientResourcePanelLayout);
        jClientResourcePanelLayout.setHorizontalGroup(
            jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRent2Button, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jRent6Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResponse)))
                    .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearchButton)
                            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                                .addComponent(jIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jClientResourcePanelLayout.setVerticalGroup(
            jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientResourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRent2Button)
                .addGap(18, 18, 18)
                .addComponent(jRent6Button)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jClientResourcePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jClientResourcePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jResourceList.setEditable(false);
        jResourceList.setColumns(20);
        jResourceList.setRows(5);
        jScrollPane4.setViewportView(jResourceList);

        javax.swing.GroupLayout jResourceListPanelLayout = new javax.swing.GroupLayout(jResourceListPanel);
        jResourceListPanel.setLayout(jResourceListPanelLayout);
        jResourceListPanelLayout.setHorizontalGroup(
            jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResourceListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jResourceListPanelLayout.setVerticalGroup(
            jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResourceListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jUserBooksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBorrowedResources.setEditable(false);
        jBorrowedResources.setColumns(20);
        jBorrowedResources.setRows(5);
        jScrollPane1.setViewportView(jBorrowedResources);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Borrowed Resources");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Early Return");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Due / Late returns");

        jDueOverdue.setColumns(20);
        jDueOverdue.setRows(5);
        jScrollPane5.setViewportView(jDueOverdue);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel10)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jUserBooksPanelLayout = new javax.swing.GroupLayout(jUserBooksPanel);
        jUserBooksPanel.setLayout(jUserBooksPanelLayout);
        jUserBooksPanelLayout.setHorizontalGroup(
            jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUserBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jUserBooksPanelLayout.setVerticalGroup(
            jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMainUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResourceListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMessageBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessageBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUserBooksPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMainUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jResourceListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        
        
        //Get input from Login text boxes
        jUserName.getText();
        jPassword.getText();
        
        //Preset user
        String clientOneUsername = "Ryan";
        String clientOnePassword = "Carter";
        
        String clientTwoUsername = "User2";
        String clientTwoPassword = "User2";
        
        String clientThreeUsername = "User3";
        String clientThreePassword = "User3";
        
        //Preset Admin
        String adminUserName = "Admin";
        String adminPassword = "Password";
        
        
        
        
         
        //Client
        
        //Checking if User exists
        if(jUserName.getText().equals(clientOneUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientOnePassword)){
                
                
                
                currentUser = new Client("Ryan", "Carter", false, "Ryan", "Carter");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();
                             
            }
        }
        else if(jUserName.getText().equals(clientTwoUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientTwoPassword)){
                
                             
                
                currentUser = new Client("User2", "User2", false, "Joe", "Bloggs");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();

                             
            }
        }
        else if(jUserName.getText().equals(clientThreeUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientThreePassword)){
                
                              
                
                currentUser = new Client("User3", "User3", false, "Jane", "Doe");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();             
            }
        }
        //Checking Admin
        else if(jUserName.getText().equals(adminUserName)){
            
            System.out.println("Admin Username Correct");
            
            if(jPassword.getText().equals(adminPassword)){
               
                System.out.println("Password correct, Welcome Admin");

                //Display Admin UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);                                


            }
        }
        
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutButtonActionPerformed
        // TODO add your handling code here:
        
        jLoginPanel.setVisible(true);
        jUserName.setText("");
        jPassword.setText("");
        jUserPanel.setVisible(false);
        jResourceListPanel.setVisible(false);
        jClientResourcePanel.setVisible(false);
        jMessageBoardPanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jUserBooksPanel.setVisible(false);
        
    }//GEN-LAST:event_jLogoutButtonActionPerformed

    private void jResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResponseActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
     try{   
        System.out.println("Searching");    
        
        int idTest;
        
        
        jResponse.getText();      
     
        idTest = Integer.parseInt(jIdSearch.getText());
        System.out.println("Searching for: " + idTest);

        for (Resource i : resourceList){
            if(i.getID() == idTest){
                
                String foundName = i.getResourceName();
                jResponse.setText(foundName);
                
                if(i.isAvailable()){
                    jAvailable.setText("Available");
                    jRent2Button.setEnabled(true);
                    jRent6Button.setEnabled(true);
                    
                    foundID = i;
                    
                }    
                else{                  
                    jAvailable.setText("Unavailable");
                    jRent2Button.setEnabled(false);
                    jRent6Button.setEnabled(false);
                
                }
                
                break;
            }
            else{
                jResponse.setText("Resource not found");
            }
        }
     }catch(NumberFormatException e){     
   
    }//GEN-LAST:event_jSearchButtonActionPerformed
    
    
    }
    
    private void jRent2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRent2ButtonActionPerformed
        // TODO add your handling code here:
        
        //Rent resource for 2 weeks
        
        Borrowing(foundID.getID(),foundID.getResourceName(), 14);
        
        foundID.setAvailable(false);
        
        LoadResources();
        LoadBorrowed();
        
        
        
        
    }//GEN-LAST:event_jRent2ButtonActionPerformed

    private void jRent6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRent6ButtonActionPerformed
        // TODO add your handling code here:
        
        //Rent resource for 6 weeks
        
        Borrowing(foundID.getID(),foundID.getResourceName(), 42);
        
        foundID.setAvailable(false);
        
        LoadResources();
        LoadBorrowed();
        
    }//GEN-LAST:event_jRent6ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    public void createResources(){
        
        DVD planetEarth = new DVD("Planet Earth Boxset", 1, 500, "dvd", true,  "Not Overdue");
        Book mobyDick = new Book("Moby Dick", 2, 500, "Book", true, "Not Overdue");
        Magazine artNews = new Magazine("ARTnews", 3, 500, "Magazine",true, "Not Overdue");
        Book religousStudies = new Book("Religious Studies", 4, 500, "Book",true, "Not Overdue");
        Book javaForDummies = new Book("Java For Dummies", 5, 500, "Book",true, "Not Overdue");
        
        
        
        resourceList = new ArrayList();
        
        resourceList.add(planetEarth);
        resourceList.add(mobyDick);
        resourceList.add(artNews);
        resourceList.add(religousStudies);
        resourceList.add(javaForDummies);     
        
        
        
        
        
    }
    
    public void Borrowing(int tempResourceID, String tempResourceName, int tempDaysBorrowed){
    
        String userName;
        int  ID;
        String resourceName;
        int days;
        
              
        userName = currentUser.getFirstName();
        
        ID = tempResourceID;
        
        days = tempDaysBorrowed;
        
        resourceName = tempResourceName;
        
        jAvailable.setText("");
        jResponse.setText("");  
        jIdSearch.setText("");
        
         
        //System.out.println(userName + " " + tempResourceID + " " + tempDaysBorrowed);
        
        Borrow borrow = new Borrow(userName, ID,resourceName, days);     
        
        
        borrowedList.add(borrow);
    
    }
       
    
    
            
    public void LoadResources(){
        
        
        
        String resourceListString = "";
        
        for (Resource i : resourceList)
        {
            //boolean available;                      
            
            if(i.isAvailable())         
                resourceListString += i.getID() + ".  " + i.getResourceName() + " " + i.getTypeName() + "\n";
        }
        
        jResourceList.setText(resourceListString);
        
        jResourceList.setEditable(false);          
                
    }
    
    public void LoadBorrowed(){
        
        String borrowedListString = "";
        
        for (Borrow i : borrowedList){
            if(i.getBorrower().equals(currentUser.getFirstName())){
                borrowedListString += i.getResourceID() + " " + i.getResourceName() + " Days remaining: " + i.getDaysRemaining() + "\n";
            }
            
            
        }
        
        jBorrowedResources.setText(borrowedListString);
    }
    
    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAdminMessagePanel;
    private javax.swing.JTextField jAvailable;
    private javax.swing.JTextArea jBorrowedResources;
    private javax.swing.JPanel jClientResourcePanel;
    private javax.swing.JTextArea jDueOverdue;
    private javax.swing.JTextField jIdSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JButton jLogoutButton;
    private javax.swing.JPanel jMainUserPanel;
    private javax.swing.JPanel jMessageBoard;
    private javax.swing.JPanel jMessageBoardPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jRent2Button;
    private javax.swing.JButton jRent6Button;
    private javax.swing.JTextArea jResourceList;
    private javax.swing.JPanel jResourceListPanel;
    private javax.swing.JTextField jResponse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel jUserBooksPanel;
    private javax.swing.JTextField jUserName;
    private javax.swing.JPanel jUserPanel;
    private javax.swing.JLabel jWelcome;
    // End of variables declaration//GEN-END:variables
}
