/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Book;
import Model.Borrow;
import Model.Client;
import Model.DVD;
import Model.Magazine;
import Model.Message;
import Model.Resource;
import java.util.ArrayList;
import java.time.LocalDate;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ryan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    //private ClientUI clientUI;
    
    private ArrayList<Resource> resourceList;    
    
    public ArrayList<Borrow> borrowedList;
    
    public ArrayList<Borrow> lateResources;
    
    public ArrayList<Message> messageList;
    
    public ArrayList <Borrow> dueLateResources;
    
    public Message message;
    
    public String messageString = "";
    
    public Client currentUser;
    
    public Resource foundID;
    
    public int returningID;
    
    public int index;
    
    public LocalDate currentDate;
    
    
    
    DefaultListModel listModel = new DefaultListModel();
    
    public Login() {
        initComponents();
        
        createResources();
        
        borrowedList = new ArrayList();
        
        messageList = new ArrayList();
        
        dueLateResources = new ArrayList();
        
        currentDate = LocalDate.now();
        
        //Make all panels except the Log in panel invisible
        jUserPanel.setVisible(false);
        jResourceListPanel.setVisible(false);
        jClientResourcePanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jAdminMessagePanel.setVisible(false);
        jMessageBoardPanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jUserBooksPanel.setVisible(false);
        jAdminPanel.setVisible(false);
        jError.setVisible(false);
        
        
        messageString = "Welcome to the Apex Library resource management software. This is an early version ";
        
        System.out.println(messageString);
        
        Message automatedMessage = new Message("Automated Message: ", messageString);
        
        messageList.add(automatedMessage);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jMainUserPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLoginPanel = new javax.swing.JPanel();
        jUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jUserPanel = new javax.swing.JPanel();
        jWelcome = new javax.swing.JLabel();
        jLogoutButton = new javax.swing.JButton();
        jMessageBoardPanel = new javax.swing.JPanel();
        jAdminMessagePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jAdminMessage = new javax.swing.JTextArea();
        jAdminSend = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMessageBoard = new javax.swing.JTextArea();
        jResourceListPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jClientResourcePanel = new javax.swing.JPanel();
        jRent2Button = new javax.swing.JButton();
        jRent6Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jIdSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSearchButton = new javax.swing.JButton();
        jResponse = new javax.swing.JTextField();
        jAvailable = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jResourceList = new javax.swing.JTextArea();
        jUserBooksPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBorrowedResources = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jReturnSearch = new javax.swing.JTextField();
        jReturnSearchButton = new javax.swing.JButton();
        jReturnSearchDisplay = new javax.swing.JTextField();
        jReturnResource = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jDueOverdue = new javax.swing.JTextArea();
        jAdminPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jNewResourceName = new javax.swing.JTextField();
        jNewResourceClass = new javax.swing.JTextField();
        jNewResourceType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jError = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jAdvanceTime1Day = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMainUserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Apex Library Resource Management");

        jLabel1.setText("Username:");

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLoginButton.setText("Log In");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1))
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUserName)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLoginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLoginButton)
                .addContainerGap())
        );

        jWelcome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jWelcome.setText("Welcome User");

        jLogoutButton.setText("Log Out");
        jLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jUserPanelLayout = new javax.swing.GroupLayout(jUserPanel);
        jUserPanel.setLayout(jUserPanelLayout);
        jUserPanelLayout.setHorizontalGroup(
            jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWelcome)
                .addGap(36, 36, 36)
                .addComponent(jLogoutButton)
                .addGap(34, 34, 34))
        );
        jUserPanelLayout.setVerticalGroup(
            jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLogoutButton))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jMainUserPanelLayout = new javax.swing.GroupLayout(jMainUserPanel);
        jMainUserPanel.setLayout(jMainUserPanelLayout);
        jMainUserPanelLayout.setHorizontalGroup(
            jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(27, 27, 27))
            .addGroup(jMainUserPanelLayout.createSequentialGroup()
                .addGroup(jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jMainUserPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jMainUserPanelLayout.setVerticalGroup(
            jMainUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMessageBoardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jAdminMessage.setColumns(20);
        jAdminMessage.setRows(5);
        jAdminMessage.setToolTipText("");
        jAdminMessage.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jAdminMessage);

        jAdminSend.setText("Send");
        jAdminSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAdminMessagePanelLayout = new javax.swing.GroupLayout(jAdminMessagePanel);
        jAdminMessagePanel.setLayout(jAdminMessagePanelLayout);
        jAdminMessagePanelLayout.setHorizontalGroup(
            jAdminMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdminMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdminMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAdminSend, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jAdminMessagePanelLayout.setVerticalGroup(
            jAdminMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAdminMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdminSend)
                .addGap(14, 14, 14))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Message Board");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);

        jMessageBoard.setEditable(false);
        jMessageBoard.setColumns(2);
        jMessageBoard.setLineWrap(true);
        jMessageBoard.setRows(5);
        jMessageBoard.setWrapStyleWord(true);
        jMessageBoard.setAutoscrolls(false);
        jScrollPane2.setViewportView(jMessageBoard);

        javax.swing.GroupLayout jMessageBoardPanelLayout = new javax.swing.GroupLayout(jMessageBoardPanel);
        jMessageBoardPanel.setLayout(jMessageBoardPanelLayout);
        jMessageBoardPanelLayout.setHorizontalGroup(
            jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jAdminMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMessageBoardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49)))
                .addContainerGap())
        );
        jMessageBoardPanelLayout.setVerticalGroup(
            jMessageBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMessageBoardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jAdminMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jResourceListPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRent2Button.setText("Rent - 2 weeks");
        jRent2Button.setEnabled(false);
        jRent2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRent2ButtonActionPerformed(evt);
            }
        });

        jRent6Button.setText("Rent - 6 weeks");
        jRent6Button.setEnabled(false);
        jRent6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRent6ButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Borrowing");

        jIdSearch.setColumns(1);
        jIdSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel7.setText("ID");

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jResponse.setEditable(false);
        jResponse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResponseActionPerformed(evt);
            }
        });

        jAvailable.setEditable(false);

        javax.swing.GroupLayout jClientResourcePanelLayout = new javax.swing.GroupLayout(jClientResourcePanel);
        jClientResourcePanel.setLayout(jClientResourcePanelLayout);
        jClientResourcePanelLayout.setHorizontalGroup(
            jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRent2Button, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jRent6Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jResponse)))
                    .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSearchButton)
                            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                                .addComponent(jIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jClientResourcePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jClientResourcePanelLayout.setVerticalGroup(
            jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientResourcePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(87, 87, 87)
                .addGroup(jClientResourcePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRent2Button)
                .addGap(18, 18, 18)
                .addComponent(jRent6Button)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jClientResourcePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jClientResourcePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jResourceList.setEditable(false);
        jResourceList.setColumns(20);
        jResourceList.setRows(5);
        jScrollPane4.setViewportView(jResourceList);

        javax.swing.GroupLayout jResourceListPanelLayout = new javax.swing.GroupLayout(jResourceListPanel);
        jResourceListPanel.setLayout(jResourceListPanelLayout);
        jResourceListPanelLayout.setHorizontalGroup(
            jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResourceListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jResourceListPanelLayout.setVerticalGroup(
            jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResourceListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResourceListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(2, 2, 2))
        );

        jUserBooksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBorrowedResources.setEditable(false);
        jBorrowedResources.setColumns(20);
        jBorrowedResources.setRows(5);
        jScrollPane1.setViewportView(jBorrowedResources);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Borrowed Resources");

        jLabel9.setText("ID");

        jReturnSearchButton.setText("Search");
        jReturnSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnSearchButtonActionPerformed(evt);
            }
        });

        jReturnSearchDisplay.setEditable(false);

        jReturnResource.setText("Return");
        jReturnResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReturnResourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jReturnSearchButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jReturnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jReturnResource))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jReturnSearchDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jReturnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReturnSearchDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReturnSearchButton)
                    .addComponent(jReturnResource))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Late and Due returns");

        jDueOverdue.setColumns(20);
        jDueOverdue.setRows(5);
        jScrollPane5.setViewportView(jDueOverdue);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jUserBooksPanelLayout = new javax.swing.GroupLayout(jUserBooksPanel);
        jUserBooksPanel.setLayout(jUserBooksPanelLayout);
        jUserBooksPanelLayout.setHorizontalGroup(
            jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUserBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jUserBooksPanelLayout.setVerticalGroup(
            jUserBooksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUserBooksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jAdminPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("New Resource");

        jLabel12.setText("Resource Name");

        jLabel13.setText("Dewey Class");

        jLabel14.setText("Resource Type");

        jButton1.setText("Create Resource");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Note: Use lower case when creating a new resource");

        jError.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNewResourceName)
                                    .addComponent(jNewResourceClass, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                            .addComponent(jLabel11)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jNewResourceType, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jError, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jNewResourceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jNewResourceClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jNewResourceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jAdminPanelLayout = new javax.swing.GroupLayout(jAdminPanel);
        jAdminPanel.setLayout(jAdminPanelLayout);
        jAdminPanelLayout.setHorizontalGroup(
            jAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jAdminPanelLayout.setVerticalGroup(
            jAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Debug");

        jAdvanceTime1Day.setText("+1 day");
        jAdvanceTime1Day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdvanceTime1DayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jAdvanceTime1Day))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdvanceTime1Day)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMainUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResourceListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMessageBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMainUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jResourceListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUserBooksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMessageBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        
        
        //Get input from Login text boxes
        jUserName.getText();
        jPassword.getText();
        
        //Preset user
        String clientOneUsername = "User1";
        String clientOnePassword = "User1";
        
        String clientTwoUsername = "User2";
        String clientTwoPassword = "User2";
        
        String clientThreeUsername = "User3";
        String clientThreePassword = "User3";
        
        //Preset Admin
        String adminUserName = "Admin";
        String adminPassword = "Admin";
        
        
        
        
         
        //Client
        
        //Checking if User exists
        if(jUserName.getText().equals(clientOneUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientOnePassword)){
                
                
                
                currentUser = new Client("Jane", "Smith", false, "Ryan", "Carter");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();
                LoadMessages();
                             
            }
        }
        else if(jUserName.getText().equals(clientTwoUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientTwoPassword)){
                
                             
                
                currentUser = new Client("User2", "User2", false, "Joe", "Bloggs");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();
                LoadMessages();

                             
            }
        }
        else if(jUserName.getText().equals(clientThreeUsername)){
            
            System.out.println("Client Username Correct");
            
            if(jPassword.getText().equals(clientThreePassword)){
                
                              
                
                currentUser = new Client("User3", "User3", false, "Jane", "Doe");
                
                System.out.println("Password correct, Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                jWelcome.setText("Welcome " + currentUser.getFirstName() + " " + currentUser.getLastName());
                
                
               
                //Display User UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jClientResourcePanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);
                jUserBooksPanel.setVisible(true);
                
                LoadResources();
                LoadBorrowed();
                LoadMessages();
            }
        }
        //Checking Admin
        else if(jUserName.getText().equals(adminUserName)){
            
            System.out.println("Admin Username Correct");
            
            if(jPassword.getText().equals(adminPassword)){
               
                System.out.println("Password correct, Welcome Admin");
                
                
                currentUser = new Client("Admin", "Admin", false, "Administrator", "Administrator");

                //Display Admin UI
                jLoginPanel.setVisible(false);
                jUserPanel.setVisible(true);
                jResourceListPanel.setVisible(true);
                jMessageBoardPanel.setVisible(true);
                jMessageBoard.setVisible(true);   
                jAdminMessagePanel.setVisible(true);
                jAdminMessage.setVisible(true);
                jAdminPanel.setVisible(true);
                
                LoadResources();
                LoadMessages();

            }
        }
        
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutButtonActionPerformed
        // TODO add your handling code here:
        
        jLoginPanel.setVisible(true);
        jUserName.setText("");
        jPassword.setText("");
        jUserPanel.setVisible(false);
        jResourceListPanel.setVisible(false);
        jClientResourcePanel.setVisible(false);
        jMessageBoardPanel.setVisible(false);
        jMessageBoard.setVisible(false);
        jUserBooksPanel.setVisible(false);
        jAdminMessage.setVisible(false);
        jAdminPanel.setVisible(false);
        
    }//GEN-LAST:event_jLogoutButtonActionPerformed

    private void jResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jResponseActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        // TODO add your handling code here:
     try{   
        System.out.println("Searching");    
        
        int idTest;
        
        
        jResponse.getText();      
     
        idTest = Integer.parseInt(jIdSearch.getText());
        System.out.println("Searching for: " + idTest);
        
        for (Resource i : resourceList){
            if(i.getID() == idTest){
                
                String foundName = i.getResourceName();
                jResponse.setText(foundName);
                
                if(i.isAvailable()){
                    jAvailable.setText("Available");
                    jRent2Button.setEnabled(true);
                    jRent6Button.setEnabled(true);
                    
                    foundID = i;
                    
                }    
                else{                  
                    jAvailable.setText("Unavailable");
                    jRent2Button.setEnabled(false);
                    jRent6Button.setEnabled(false);
                
                }
                
                break;
            }
            else{
                jResponse.setText("Resource not found");
            }
        }
     }catch(NumberFormatException e){     
   
    }//GEN-LAST:event_jSearchButtonActionPerformed
    
    
    }
    
    private void jRent2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRent2ButtonActionPerformed
        // TODO add your handling code here:
        
        //Rent a resource for 2 weeks
        
        Borrowing(foundID.getID(),foundID.getResourceName(), 14);
        
        foundID.setAvailable(false);
        
        LoadResources();
        LoadBorrowed();
        
        
        
        
    }//GEN-LAST:event_jRent2ButtonActionPerformed

    private void jRent6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRent6ButtonActionPerformed
        // TODO add your handling code here:
        
        //Rent resource for 6 weeks
        
        Borrowing(foundID.getID(),foundID.getResourceName(), 42);
        
        foundID.setAvailable(false);
        
        LoadResources();
        LoadBorrowed();
        
    }//GEN-LAST:event_jRent6ButtonActionPerformed

    private void jReturnSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnSearchButtonActionPerformed
        // TODO add your handling code here:
        try{ 
            
            System.out.println("Searching for resource \n ------------------------------------------------------------------");
            
            jReturnSearch.getText();

            int idTest;

            idTest = Integer.parseInt(jReturnSearch.getText());

            for (Borrow i : borrowedList){
                if(i.getResourceID() == idTest){

                    String returnName = i.getResourceName();

                    jReturnSearchDisplay.setText(returnName);
                    
                    returningID = i.getResourceID();
                    
                    
                    
                    index = borrowedList.indexOf(i);
                    
                    
                }
                else{
                    jReturnSearchDisplay.setText("Resource not found");
                }
            }
        }
        catch(NumberFormatException e){  
            
        }
        
    }//GEN-LAST:event_jReturnSearchButtonActionPerformed

    private void jReturnResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReturnResourceActionPerformed
        // TODO add your handling code here:
        
        try{ 
         
            for (Resource k : resourceList){

                if (k.getID() == returningID)            
                {
                    k.setAvailable(true);

                    borrowedList.remove(index);
                    
                    jReturnSearch.setText("");
                    jReturnSearchDisplay.setText("");
                    

                    LoadResources();
                    LoadBorrowed();
                }
            }
        }
        catch(IndexOutOfBoundsException e){  
            
        }
        
        
    }//GEN-LAST:event_jReturnResourceActionPerformed

    private void jAdminSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminSendActionPerformed
        // TODO add your handling code here:
        
        if(jAdminMessage.getText() != null){
            
            Message message = new Message(currentUser.getFirstName(), jAdminMessage.getText());
            
            messageList.add(message);
            LoadMessages();
            
        }
    }//GEN-LAST:event_jAdminSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jNewResourceName.getText();
        jNewResourceClass.getText();
        jNewResourceType.getText();
        
        if(jNewResourceName.getText() != null){
            if(jNewResourceClass.getText() != null){
                if(jNewResourceType.getText() != null ){
        
                    String name = jNewResourceName.getText();
                    String type = jNewResourceType.getText();
                    int deweyClass = Integer.parseInt(jNewResourceClass.getText());
                    
                    int nextIndex;
                    
                    nextIndex = resourceList.size() + 1;

                    switch(type){
                        case "book":
                            Book newBook = new Book(name, nextIndex,deweyClass, "Magazine", true, false);
                            
                            resourceList.add(newBook);
                            break;
                        case "dvd":
                            DVD newDVD = new DVD(name, nextIndex,deweyClass, "Magazine", true, false);
                            
                            resourceList.add(newDVD);
                            break;
                        case "magazine":
                            Magazine newMagazine = new Magazine(name, nextIndex,deweyClass, "Magazine", true, false);
                            
                            resourceList.add(newMagazine);
                            break;
                    }
                    
                    jNewResourceName.setText("");
                    jNewResourceClass.setText("");
                    jNewResourceType.setText("");
                    LoadResources();
                    
                    
                }
                jError.setVisible(true);
                jError.setText("Invalid type given");
            }
            jError.setVisible(true);
            jError.setText("No/invalid Class given, Use Dewey Classification to give a valid input");
        }
        else{
            jError.setVisible(true);
            jError.setText("No Name given");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jAdvanceTime1DayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdvanceTime1DayActionPerformed
        // TODO add your handling code here:
        
        currentDate = currentDate.plusDays(1);
        
        LoadResources();
        LoadMessages();
        LoadBorrowed();
        
    }//GEN-LAST:event_jAdvanceTime1DayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    
    public void createResources(){
        
        DVD planetEarth = new DVD("Planet Earth Boxset", 1, 500, "dvd", true,  false);
        Book mobyDick = new Book("Moby Dick", 2, 500, "Book", true, false);
        Magazine artNews = new Magazine("ARTnews", 3, 500, "Magazine",true, false);
        Book religousStudies = new Book("Religious Studies", 4, 500, "Book",true, false);
        Book javaForDummies = new Book("Java For Dummies", 5, 500, "Book",true, false);
        
        
        
        resourceList = new ArrayList();
        
        resourceList.add(planetEarth);
        resourceList.add(mobyDick);
        resourceList.add(artNews);
        resourceList.add(religousStudies);
        resourceList.add(javaForDummies);     
        
    }
    
    public void Borrowing(int tempResourceID, String tempResourceName, int tempDaysBorrowed){
    
        String userName;
        int  ID;
        String resourceName;
        LocalDate returnDate;
        
              
        userName = currentUser.getFirstName();
        
        ID = tempResourceID;
        
        returnDate = plusDays(tempDaysBorrowed);
        
        resourceName = tempResourceName;
        
        jAvailable.setText("");
        jResponse.setText("");  
        jIdSearch.setText("");
        
         
        System.out.println(userName + " " + tempResourceID + " " + tempDaysBorrowed);
        
        Borrow borrow = new Borrow(userName, ID,resourceName, returnDate, tempDaysBorrowed);     
        
        
        borrowedList.add(borrow);
    
    }
           
    public void LoadMessages(){
        
        String messageListString = "";
        
        for (Message i : messageList){
            
            messageListString += i.getSenderID() + ": " + i.getMessageContents() + "\n----------------------------------------\n";
            
        }
        
        jMessageBoard.setText(messageListString);
    
    }
            
            
            
    public void LoadResources(){
        
        
        
        String resourceListString = "";
        
        for (Resource i : resourceList)
        {
            //boolean available;                      
            
            if(i.isAvailable())         
                resourceListString += i.getID() + ".  " + i.getResourceName() + " " + i.getTypeName() + "\n";
        }
        
        jResourceList.setText(resourceListString);
        
        jResourceList.setEditable(false);          
                
    }
    
    public void LoadBorrowed(){
        
        String borrowedListString = "";
        String dueLateString = "";
        
        for (Borrow i : borrowedList){
            if(i.getBorrower().equals(currentUser.getFirstName())){
                
                
                
                                              
                if(i.getReturnDate().isAfter(currentDate)){
                    borrowedListString += i.getResourceID() + " " + i.getResourceName() + " Date due: " + i.getReturnDate() + "\n";
                }
                else if (i.getReturnDate().isEqual(currentDate)){
                    dueLateString += i.getResourceID() + " " + i.getResourceName() + " Date due: " + i.getReturnDate() + "\n";
                }
                else if (i.getReturnDate().isBefore(currentDate)){
                    dueLateString += i.getResourceID() + " " + i.getResourceName() + " Date due: " + i.getReturnDate() + "\n";                  
                    
                }
                
                
                
            }          
            
        }
        
        jBorrowedResources.setText(borrowedListString);
        jDueOverdue.setText(dueLateString);
    }
    
   
    

    public LocalDate plusDays(int days){     
              
        LocalDate date = LocalDate.now();
        
        LocalDate returnDate;
        
        returnDate = date.plusDays(days);
        
        
        
        return returnDate;
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAdminMessage;
    private javax.swing.JPanel jAdminMessagePanel;
    private javax.swing.JPanel jAdminPanel;
    private javax.swing.JButton jAdminSend;
    private javax.swing.JButton jAdvanceTime1Day;
    private javax.swing.JTextField jAvailable;
    private javax.swing.JTextArea jBorrowedResources;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jClientResourcePanel;
    private javax.swing.JTextArea jDueOverdue;
    private javax.swing.JTextField jError;
    private javax.swing.JTextField jIdSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JButton jLogoutButton;
    private javax.swing.JPanel jMainUserPanel;
    private javax.swing.JTextArea jMessageBoard;
    private javax.swing.JPanel jMessageBoardPanel;
    private javax.swing.JTextField jNewResourceClass;
    private javax.swing.JTextField jNewResourceName;
    private javax.swing.JTextField jNewResourceType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jRent2Button;
    private javax.swing.JButton jRent6Button;
    private javax.swing.JTextArea jResourceList;
    private javax.swing.JPanel jResourceListPanel;
    private javax.swing.JTextField jResponse;
    private javax.swing.JButton jReturnResource;
    private javax.swing.JTextField jReturnSearch;
    private javax.swing.JButton jReturnSearchButton;
    private javax.swing.JTextField jReturnSearchDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JPanel jUserBooksPanel;
    private javax.swing.JTextField jUserName;
    private javax.swing.JPanel jUserPanel;
    private javax.swing.JLabel jWelcome;
    // End of variables declaration//GEN-END:variables
}
